# command prefix (like screen)
set -g prefix C-j
unbind C-b
bind C-j send-prefix

# basic settings
set-window-option -g mode-keys vi # vi key
set-option -g status-keys vi
set-window-option -g utf8 on # utf8 support
set-window-option -g mode-mouse off # disable mouse

# splitting and cycling
set-option -g mouse-select-pane off
unbind %
bind | split-window -h # horizontal split
unbind '"'
bind _ split-window -v # vertical split

# window title
set-option -g set-titles on
set-window-option -g automatic-rename on # auto name

# No visual activity
set -g visual-activity off
set -g visual-bell off

#next tab
bind-key -n C-right next

#previous tab
bind-key -n C-left prev

# pane resizing
unbind-key j        ; bind-key j     resize-pane -D 5
unbind-key k        ; bind-key k     resize-pane -U 5
unbind-key h        ; bind-key h     resize-pane -L 5
unbind-key l        ; bind-key l     resize-pane -R 5

set -g default-terminal "xterm-256color"

set-option -g set-remain-on-exit on
bind-key x kill-pane

set-option -g history-limit 10000

set -g default-command "reattach-to-user-namespace -l /bin/zsh"
