vim.g.mapleader = ","
vim.wo.cursorline = true
-- FIXME vim.wo.cursorline.ctermbg = 236
vim.opt.clipboard = "unnamedplus"
vim.opt.expandtab = true
vim.opt.foldlevel = 99
vim.opt.foldmethod = "indent"
vim.opt.foldcolumn = "1"
vim.opt.wrap = false
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.shiftwidth = 2
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.tabstop = 2
vim.opt.updatetime = 50
vim.opt.showmode = false -- to get rid of thing like --INSERT--
vim.opt.showcmd = false -- to get rid of display of last command
vim.opt.shortmess = "F" -- to get rid of the file name displayed in the command line bar
vim.opt.termguicolors = true
vim.g.python_host_prog = "/usr/bin/python"
vim.g.python3_host_prog = "/usr/local/bin/python3"
