vim.g.mapleader = " "
vim.g.maplocalleader = " "
vim.g.signcolumn = "true"
vim.g.python_host_prog = "/usr/bin/python"
vim.g.python3_host_prog = "/usr/local/bin/python3"

vim.wo.cursorline = true
-- FIXME vim.wo.cursorline.ctermbg = 236
vim.o.clipboard = "unnamedplus"
vim.o.expandtab = true
vim.o.foldlevel = 99
vim.o.foldmethod = "indent"
vim.o.foldcolumn = "0"
vim.o.wrap = false
vim.o.backup = false
vim.o.swapfile = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.shiftwidth = 2
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.softtabstop = 2
vim.o.tabstop = 2
vim.o.updatetime = 50
vim.o.showmode = false -- to get rid of thing like --INSERT--
vim.o.showcmd = false -- to get rid of display of last command
vim.o.shortmess = "F" -- to get rid of the file name displayed in the command line bar
vim.o.termguicolors = true
vim.o.hlsearch = false
vim.o.breakindent = false
vim.o.completeopt = 'menuone,noselect'
